package com.gopal.fast.vid.NewImplement.model;

 public enum AdharGuide {
     adharguide1( "➺ Personal loan is also like any other loan. When a person takes a loan from a bank to meet his personal financial requirement. So it is called personal loan. Personal loan is of both types short term long term. Nowadays almost all banks in India provide personal loans. You can take a personal loan from any bank according to your need. But all the banks have their own different term and conditions. \n\n➺ Personal loan is considered the most unsecured. Personal loan is available for a short period only. You cannot take a personal loan like other professional loans. You can take a personal loan from 1 year to 5 years. You can get a personal loan from a minimum of Rs 50000 to a maximum of Rs 500000. You can take a personal loan for any of your needs such as to go somewhere, to buy TV, mobile, etc., to get the house repaired, to start a business or to pay the credit card. \n\n➺ 1. Banks and Non-Banking Financial Companies (NBFCs) offer personal loans for a variety of needs. These needs include marriages, home repairs, vacations, etc. \n\n➺ 2. Personal loans are given without any guarantee. This means that banks do not ask you to pledge any asset in return. In this way, the hands of banks are tied in their recovery. This is the reason that the rate of interest is higher in comparison to other secured loans. \n\n➺ 3. Banks have kept very strict criteria in giving personal loans. These include the income, credit and employment history of the customer and the ability to repay the loan. The loan is approved only after reviewing all these aspects. \n\n➺ 4. Apart from interest, customers also have to pay loan processing fees. Banks or NBFCs can charge prepayment penalty if they want. By the way, most of the banks do not levy prepayment penalty. Prepayment is the payment of the loan ahead of time. \n\n➺ 5. Many times banks offer pre-approved loan facility based on the financial history of the customer. Not only does it offer affordable interest rates, but there is not much paperwork involved in giving the loan. In this type of loan, money is deposited in the customer\\'s account in three to four days."),
     adharguide2( "➺ Although Aadhaar card has not been made mandatory for loan borrowers till now, yet it can make loan processing very easy. Aadhar card as ID proof The time and effort that the bank officials had to put in to verify the documents of the loan applicant after their acceptance has been reduced considerably. basic document to aadhar card In the form of online loan taken, customer verification is done with e-KYC. The use of Aadhar card in loan is the basis of lending.Through e-KYC Due to the online verification of the applicant, the instant loan which is claimed to be disbursed within hours becomes possible. online loans better loans It can also be obtained by furnishing a scanned copy of your Aadhar card as the only document for identification."),
     adharguide3( "➺ In today\\'s time, such an ID runs a lot, which has become a very famous ID in today\\'s time, yes friends, let\\'s talk about how the ID of Aadhar card is in the Aadhar card, which you can give for any kind of ID at any place. And it is considered as your complete ID. On the basis of Aadhar card, you can provide any kind of thing and you can take anything from anyone through Aadhar card, you can take your SIM or your bank. Can open account can take loan can take car can take gas cylinder And you can include Aadhar card in any of your documents, this is a very big advantage of the Indian government that if you take anything on the basis of Aadhar card number, then when your thing gets lost. If it is lost somewhere or due to some reason, then after that you can get that thing again with your Aadhar card. Aadhar card is such a thing that you use in everything like if you take mobile sim and If you want to get your sim started soon \n\n➺ So for that you give your Aadhaar number to the shopkeeper and then that shopkeeper will come to you to put any finger in your hand on his machine so that the marks of your hand will come in that machine and then your Aadhar card will be verified and with that you can get your SIM started very quickly because when you put your figure on the machine, it goes to the headquarters of the SIM giving company, from where immediately your wife Let us turn on the SIM and earlier when you used to give the ID, then after three to four days that ID used to reach the headquarters of the company, after that your SIM used to start, so nowadays Aadhaar card is also very useful for getting any work done online. is proving to be beneficial. And nowadays, it is very important to have Aadhar card for almost all government and private work, if you do not have Aadhar card then you may have to face a lot of problem to get any government or private work done because today\\'s In today\\'s time, Aadhar card is sought everywhere.Although you must have heard about many types of loans, home loans, car loans, or loans for any kind of agricultural machinery are given by the government on very good loans, but you have probably never heard of it. It will happen that loan from Aadhar card Yes friends, today we will give you information about taking loan from Aadhar card in this post because you can also take loan from your Aadhar card."),
     adharguide4( "➺ Well friends, you can take many different types of loans because in today\\'s time the loan company is giving very good loans, but when you take a loan from any company, the company takes some important documents from you before and on the basis of them, the company gives you a loan, but many people have it very difficult to fulfill those documents, so those people are not able to take the loan, then if you also want to take a loan or are thinking of taking a loan, you are stupid. So let me tell you that you can take loan against Aadhar card without any problem and you get it very easily on Aadhar card. When you have to take a loan online, the company asks for a lot of documents from you and at that time you have a lot of trouble, but if you want to take a loan online, Aadhar card is such a thing. So that you can take online loan very easily. You can take a loan online very easily by using your Aadhar card and if you want to take loan online from your Aadhar card then you can get loan up to Rs 25 lakh on it."),
     adharguide5( "➺ 1. Taking online loan from Aadhar card is very simple but for this you need to follow some rules \n\n➺ 2. If your documents are absolutely correct, then you get a loan from the government very quickly. \n\n➺ 3. You have to accept all their conditions. If you have the ability to repay the loan, then they give you the loan very soon."),
     adharguide6( "➺ Although the loan sanctioning criteria may differ from one bank to another , some key factors determining the maximum loan amount that can be sanctioned to you include your credit score , current income level as well as liabilities . \n\n➺ A high credit score ( closer to 900 ) means you have serviced your previous loans and / or credit card dues properly , leading the lenders to feel that you are a safe borrower , leading to a higher loan amount being sanctioned . Your current income level and liability .."),
     adharguide7( "➺ Having an Aadhar card is really very important for indians as the Aadhar card is considered the most important identity card by the government. Let me tell an incident which happened in india-A 5-year-olg girls was lost on the busy streets of India. A person saw the girl crying and took the girl to the police station. The girl was too small to say anything, so they took her fingerprints and hoped that she had an aadhar card. After thay checked their sysytems,they found out the girls Aadhar card Status and the small 5-year-old girls was safely sent to her home!"),
     adharguide8( "➺ If you want to build your own house. And you don\\'t have enough money for this. Also if you want to start your own business. And your financial condition is not strong. You want to get loan to grow your business. But you do not have any property documents. Which are taken as a guarantee to get the loan in the bank. So you can get loan up to Rs 25 lakh on Aadhar card. You do not need any guarantee of any kind to get loan against Aadhar card. You can apply for Aadhar Card Home Loan through bank or online. Any citizen of India can get loan through Aadhar Card Home Loan. The Government of India is operating the Aadhar Card Loan Scheme to strengthen the economic condition of the citizens of the country. Rebate is also provided to the farmers under this scheme."),
     adharguide9( "➺ What are the things you have to keep in mind to take online loan from Aadhar card and there are some rules, what are the rules that you need to follow, below we are giving you information about those rules. you read carefully \n\n➺ 1. A person taking an online loan with Aadhar card should be able to repay the loan. \n\n➺ 2. The person taking loan from online Aadhar card should be at least 18 years of age. \n\n➺ 3. All the information in the Aadhaar card of the person taking online loan should be absolutely correct. \n\n➺ 4. The person taking the loan should be from India. \n\n➺ 5. If you want to take online loan from Aadhar card, then for that you have to apply for loan a month in advance, after that the government gives you money. \n\n➺ 6. If you want to take online loan from Aadhar card, then for that you should have your mobile number, address and email ID. \n\n➺ 7. For taking online loan from Aadhar card, you must have your PAN card and your bank account, only after that you can take online loan from Aadhar card. \n\n➺ 8. Because when your loan money comes, you never get it directly, it comes to you only through your bank account and therefore it is very important to have a bank account and PAN card. \n\n➺ If you fulfill all these things mentioned by us, then after that it is very easy for you to take online loan on Aadhar card and you can take loan up to 25 lakhs from your Aadhar card."),
     adharguide10( "➺ If you want to take aadhar card online loan on Aadhar work, then you must have some qualifications. \n\n➺ It is mandatory for the applicant to have an Aadhar card to take an online loan against Aadhar work. \n\n➺ Applicant\\'s age must be 18 years or above. \n\n➺ The applicant must be an Indian resident. \n\n➺ Applicant should be able to repay the loan \n\n➺ It is mandatory for the applicant to have a bank account. \n\n➺ You must have mobile number, email, home address etc. \n\n➺ Friends, first of all let me tell you this thing that you get both offline and online loan through bank on Aadhar card, decide through which medium you want to take loan and if you want to take online home loan then you You can easily get a home loan by following our mentioned methods. \n\n➺ STEP 1. \n\n➺ To take online loan on Aadhar card, you have to first go to its official website by clicking on Aadhar Housing \n\n➺ STEP 2. \n\n➺ Now a new page will open in front of you, in which you will see a drop menu, click on it home loan In this you will be asked what type of loan you want, you can choose any option according to your need. \n\n➺ STEP 3. \n\n➺ Now a new page will open in front of you, in which you will be asked for some information, fill the information that is asked in that page and click on submit. \n\n➺ STEP 4. \n\n➺ On clicking submit, you will see a registration sleep, take its print out and keep it safe with you. \n\n➺ STEP 5. \n\n➺ Now you will get a call after a few days in which you will be asked some necessary information and after giving all the information you will be called to submit the document in a nearby office where you will have to submit your documents. \n\n➺ STEP 6. \n\n➺ After the completion of all the process, you will be called to collect the money or the money will be transferred to your back account."),
     adharguide11( "➺ 1. It is mandatory for the person to be an Indian to take this loan. \n\n➺ 2. Should not have taken loan against Aadhar card from other bank. \n\n➺ 3. The person taking the loan must have bank passbook, aadhar card, pan card. \n\n➺ 4. The borrower should be able to repay the loan \n\n➺ 5. The age of the person taking the loan must be 18 years or more"),
     adharguide12( "➺ If you want to get aadhar card loan through aadhar card. So you can easily get loan through Aadhar card. ➺ To apply for Aadhar Card Home Loan either online or offline, visit the website given below aadharhousing[dot]com."),
     adharguide13( "➺ 1. First of all you have to go to the Aadhar Housing website (Aadharhousing.Com) from any of your browser. \n\n➺ 2. After this, when the website is opened in your browser, then you have to collect it on the left side above Apply for Loan. \n\n➺ 3. After this you will go to the next page, there you will get a form generated for the loan, inside that you have to fill all your details. \n\n➺ 4. After that your correct name and your email ID have to be filled in it. \n\n➺ 5. You have to fill such mobile number inside it which is available with you at all times. \n\n➺ 6. If you work in any company or in any factory or any kind of office, then you can also add the landline number there. \n\n➺ 7. After that you have to fill your correct date of birth and name of your city and name of your state. \n\n➺ 8. After that you fill your nearest Aadhar card office and then you fill your correct address where you live. \n\n➺ 9.After that you will enter the pin code of your area. Then you have to fill in that what you do. \n\n➺ 10. After that you have to fill for what purpose you want to take Aadhar loan. Like flat loan, home loan, home renovation, for some of these things. \n\n➺ 11. Then you have to do that how much loan you want to take from Aadhar card and you have to fill the money inside it. \n\n➺ 12. Then you have to fill how much you earn for one month. \n\n➺ 13. Then you have to tell that after how many days you want Aadhar loan, after 3 months 6 months or 1 year, you have to fill some one of these. \n\n➺ 14. And then in the last you have to fill that at what time you can take their call i.e. at what time you can attend their call, you have to fill the time. Then when you take all this information, after that all your things are completed and then you check them once and check them and click on submit and when your this form is successful for online aadhaar loan If you go, after that you will be called inside your nearest Aadhar office after 15 days, which you had filled inside this phone, then there you will get full information from the Aadhar office officials."),
     adharguide14( "➺ Listed below are the most important benefits of Aadhaar (12 digit unique identity number) Aadhaar based Direct Benefit Transfer (LPG Subsidy):The 12 digit individual identification number on Aadhar card is used to get LPG subsidy amount directly in the bank account \n\n➺ 1. LPG Subsidy \n\n➺ 2. Jan Dhan Yojana \n\n➺ 3. Passport in 10 days \n\n➺ 4. Digital Locker \n\n➺ 5. Voter Card Linking \n\n➺ 6. Monthly Pension \n\n➺ 7. Provident Fund \n\n➺ 8. Opening new bank account \n\n➺ 9. Digital Life Certificate \n\n➺ 10.SEBI \n\n➺ 11.Mobile number \n\n➺ 12.Driving license \n\n➺ 13.PAN card and IT return \n\n➺ 14.Investments \n\n➺ 15.Existing bank account holders \n\n➺ 16.Book Upto 12 tickets in IRCTC website in a month by linking Aadhaar");

     public String description;

     AdharGuide(String description) {
         this.description = description;
     }

     public String getDescription() {
         return description;
     }

     public void setDescription(String description) {
         this.description = description;
     }
 }
