package com.gopal.fast.vid.NewImplement.model;

public enum LoanType {
    PERSONAL_LOAN("Personal Loan", "➺ It usually depends on your income and varies based on whether you are salaried or self–employed. Usually, the banks restrict the loan amount such that your EMI is not more than 40–50% of your monthly income.\n\n➺ Any existing loans that are being serviced by the applicant are also considered when calculating the personal loan amount.\n\n➺ For the self employed, the loan value is determined on the basis of the profit earned as per the most recent acknowledged profit/Loss statement, while taking into ac…"),
    AUTO_LOAN("Car Loan", "➺ It can be used for any personal financial need and the bank will not monitor its use.\n\n➺ It can be utilised for renovating your home, marriage-related expenses, a family vacation, your childs education, purchasing latest electronic gadgets or home appliances, meeting unexpected medical expenses or any other emergencies.\n\n➺ Personal loans are also useful when it comes to investing in business, fixing your car, down payment of new house, etc."),
    HOME_LOAN("Home Loan", "➺ Simply put, it is an unsecured loan taken by individuals from a bank or a non-banking financial company (NBFC) to meet their personal needs. It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc.\n\n➺ Unlike a home or a car loan, a personal loan is not secured against any asset. As it is unsecured and the borrower does not put up collateral like gold or property to avail it, the lender, in case of a default, cannot auction.Simply put, it is an unsecured loan taken by individuals from a bank or a non-banking financial company (NBFC) to meet their personal needs.\n\n➺ It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset.\n\n➺ As it is unsecured and the borrower does not put up collateral like gold or property to avail it, the lender, in case of a default, cannot auction.Simply put, it is an unsecured loan taken by individuals from a bank or a non-banking financial company (NBFC) to meet their personal needs.\n\n➺ It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset. As it is unsecured and the borrower does not put up collateral like gold or property to avail it, the lender, in case of a default, cannot auction.\n\n➺ Simply put, it is an unsecured loan taken by individuals from a bank or a non-banking financial company (NBFC) to meet their personal needs. It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset.\n\n➺ As it is unsecured and the borrower does not put up collateral like gold or property to avail it, the lender, in case of a default, cannot auction."),
    BUSINESS_LOAN("Business Loan", "➺ It is good to compare the offers of various banks before you settle on one. Some key factors to consider when deciding on a loan provider include interest rates, loan tenure, processing fees, etc."),
    STUDENT_LOAN("Education Loan", "➺ Although it varies from bank to bank, the general criteria include your age, occupation, income, capacity to repay the loan and place of residence. To avail of a personal loan, you must have a regular income source, whether you are a salaried individual, self-employed business person or a professional.\n\n➺ An individuals eligibility is also affected by the company he is employed with, his credit history, etc."),
    MORTGAGES("Mortgages", "➺ Mortgages are loans distributed by banks to allow consumers to buy homes they can’t pay for upfront. A mortgage is tied to your home, meaning you risk foreclosure if you fall behind on payments. Mortgages have among the lowest interest rates of all loans.\n Mortgage refers to the process of offering something as a guarantee or collateral against a loan. One may come across the term when looking for secured loans.Generally, home loans of all types are secured loans. The borrower must offer their property as a security to the lender. The property mortgaged acts as collateral until the borrower has repaid the loan in full. Mortgage loans are also commonly known as loans against property.A mortgage loan can be used to either buy or build a house or refinance a property. Refinancing refers to getting a new loan for a property while the original loan is still being repaid. It is usually done to get a loan with better terms.A simple mortgage is an agreement that if the borrower is unable to repay the loan in full, the lender can sell the property that was offered as collateral and recover their amount. However, the property is not transferred to the lender.The collateral can come under the possession of the lender if the borrower fails to make full repayment of the loan during the tenure originally agreed upon."),
    PAYDAY_LOAN("Payday Loan", "➺ Payday loans are short-term, high-interest loans designed to bridge the gap from one paycheck to the next, used predominantly by repeat borrowers living paycheck to paycheck. The government strongly discourages consumers from taking out payday loans because of their high costs and interest rates.\n A payday loan is a type of short-term borrowing where a lender will extend high-interest credit based on your income. Its principal is typically a portion of your next paycheck. Payday loans charge high interest rates for short-term immediate credit. They are also called cash advance loans or check advance loans.Payday loan providers will normally require you to show proof of your income—usually your pay stubs from your employer. They will then lend you a portion of the money that you will be paid. You will have to pay the loan back within a short time, generally 30 days or less.Payday lenders take on a lot of risk, because they don’t check your ability to pay back the loan. Because of this, they normally charge very high interest rates for payday loans, and they may also charge high fees if you miss your repayments. This can be dangerous for borrowers, because it can mean that you’ll need to borrow more money to cover the cost of the first loan.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders."),
    SMALL_BUSINESS("Small Business", "➺ Everyone\\'s dream is to have a branded car with them at home. A car not only makes your life comfortable, but also reduces many difficulties. Reaching the office while battling public transport or going out for weekends, everything becomes very easy.1010 Earlier, buying a car was a big thing for anyone, because it had to spend a lump sum, but now it is very easy due to the easy availability of a car loan.1010 Banks and non-banking finance companies offer car loans on easy monthly installments, which has made it very easy to buy cars. Due to this, your budget is not deteriorated and convenience is also available.\n Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders.Payday loan providers are typically small credit merchants with physical stores that allow on-site credit applications and approval. Some payday loan services also may be available through online lenders."),
    GOLD_LOAN("Gold Loan", "➺ Although the loan sanctioning criteria may differ from one bank to another, some key factors determining the maximum loan amount that can be sanctioned to you include your credit score, current income level as well as liabilities.\n\n➺ A high credit score (closer to 900) means you have serviced your previous loans and/or credit card dues properly, leading the lenders to feel that you are a safe borrower, leading to a higher loan amount being sanctioned. Your current income level and liabil ..");
    public String description;
    public String name;

    private LoanType(String str, String str2) {
        this.name = str;
        this.description = str2;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }

    public String toString() {
        return this.name;
    }
}
