package com.gopal.fast.vid.NewImplement.model;

public enum LoanGuide {
    loanguide1("➺ Simply put , it is an unsecured loan taken by individuals from a bank or a non - banking financial company ( NBFC ) to meet their personal needs . It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. \n\n➺ Unlike a home or a car loan, a personal loan is not secured against any asset. As it is unsecured and the borrower does not put up collateral like gold or property to avail it , the lender , in case of a default , cannot auction. Simply put , it is an unsecured loan taken by individuals from a bank or a non - banking financial company ( NBFC ) to meet their personal needs . \n\n➺ It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset. \n\n➺ As it is unsecured and the borrower does not put up collateral like gold or property to avail it , the lender , in case of a default , cannot auction . Simply put , it is an unsecured loan taken by individuals from a bank or a non - banking financial company ( NBFC ) to meet their personal needs . \n\n➺ It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset. As it is unsecured and the borrower does not put up collateral like gold or property to avail it , the lender , in case of a default , cannot auction , \n\n➺ Simply put , it is an unsecured loan taken by individuals from a bank or a non - banking financial company ( NBFC ) to meet their personal needs . It is provided on the basis of key criteria such as income level, credit and employment history, repayment capacity, etc. Unlike a home or a car loan, a personal loan is not secured against any asset. \n\n➺ As it is unsecured and the borrower does not put up collateral like gold or property to avail it , the lender , in case of a default , cannot auction ."),
    loanguide2("➺ Instant Loan Guide fff - It can be used for any personal financial need and the bank will not monitor its use \n\n➺ It can be utilized for renovating your home , marriage - related expenses , family vacation , your child\\'s education , purchasing latest electronic gadgets or home appliances , meeting unexpected medical expenses any other emergencies. \n\n➺ Personal loans are also useful when it comes to investing in business, fixing your car, down payment of new house, etc."),
    loanguide3("➺ Although it varies from bank to bank, the general criteria include your age, occupation, income, ability to repay the loan and place of residence. To avail of a personal loan, you must have a regular income source, whether you are a salaried individual, self-employed business person or a professional. An individuals eligibility is also affected by the company he is employed with, his credit history, etc."),
    loanguide4("➺ It usually depends on your income and varies based on whether you are salaried or self - employed . Usually, the banks restrict the loan amount such that your EMI is not more than 40-50% of your monthly income. \n\n➺ Any existing loans that are being serviced by the applicant are also considered when calculating the personal loan amount . &gt; For the self employed , the loan value is determined on the basis of the profit earned as per the most recently acknowledged profit / loss statement , while taking into."),
    loanguide5("➺ It is good to compare the offers of various banks before you settle on one . Some key factors to consider when deciding on a loan provider include interest rates, loan tenure, processing fees, etc."),
    loanguide6("➺ Although the loan sanctioning criteria may differ from one bank to another , some key factors determining the maximum loan amount that can be sanctioned to you include your credit score , current income level as well as liabilities . \n\n➺ A high credit score ( closer to 900 ) means you have serviced your previous loans and / or credit card dues properly , leading the lenders to feel that you are a safe borrower , leading to a higher loan amount being sanctioned . Your current income level and liability .."),
    loanguide7("➺ Being unsecured loans, personal loans have a higher interest rate than those on secured home and car loans . \n\n➺ At present, many leading banks and NBFCs offer such loans at interest rates of as low as 11.49%. However , the rate applicable to a borrower is contingent on key factors , including credit score , income level , loan amount and tenure , previous relationship ( savings account , loans or credit cards ) with the lender , etc."),
    loanguide8("➺ Though the documentation requirements vary from one financial institution to another, some key documents you will have to provide with your personal loan application include: \n\n➺ Income proof (salary slip for salaried / recently acknowledged ITR for self-employed ) \n\n➺ Address proof documents Identity proof documents \n\n➺ Certified copies of degree / license ( in case of self - employed individuals )"),
    loanguide9("➺ Part payment : This amount is less than the full loan principal amount and is made before the loan amount becomes due . \n\n➺ Prepayment : When you pay off your loan in part before it becomes due as per the EMI schedule. \n\n➺ The prepayment amount may or may not be equal to the total due amount . Prepayment charges are usually in 2-5 % range of the outstanding loan amount . \n\n➺ Additionally , many banks do not allow prepayment / preclosure of loan before a specified number of EMIs have been completed . \n\n➺ Preclosure : It refers to completely paying off a personal loan before the loan tenure has ended. Just like prepayment charge , preclosure charges range from 2-5 % of the loan amount ."),
    loanguide10("➺ The approval is at the sole discretion of the loan sanctioning officer whose decision is based on the criteria specified by the bank / financial institution \n\n➺ The entire process can take between 48 hours and about two weeks. Once all the necessary documents are submitted and the verification process is completed , the loan , if sanctioned , is disbursed within seven working days by the bank . \n\n➺ Do keep all necessary documents ready along with PDC and / or signed ECS form to avoid delays in loan processing .."),
    loanguide11("➺ Since a personal loan is an unsecured loan , therefore your credit history usually plays a significant role in the approval process . Equifax , Experian and CIBIL TransUnion are the three credit reporting agencies that operate in India . \\10➺ All 3 have tie - ups with lenders and provide their credit rating services to help lenders evaluate prospective borrowers . \n\n➺ Experian India has collaboration with Union Bank of India , Sundaram Finance , Punjab National Bank , Magna Finance , Indian Bank , Axis Bank .."),
    loanguide12("➺ A higher credit score indicates that you have a good track record with respect to loans . \n\n➺ Therefore, if your credit score is high (more than 750 in case of CIBIL TransUnion), your chances of being granted a loan are much. \n\n➺ Additionally , you may be able to negotiate benefits such as a lower interest rate , higher loan amount , waiver of processing charges , etc. , by leveraging your high credit score.");

    public String description;

    LoanGuide(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
