package com.gopal.fast.vid.NewImplement.model;

public enum PanGuide {
    panguide1("➺ The full name of PAN card is Permanent Account Number. This is an identification card that is used for all types of financial transactions. \n\n➺ This is a unique card that has 10 alphanumerical characters, which the Income Tax or Income Tax Department gives to us. The PAN card is issued as a laminated card under the Indian Income Tax Act, 1961. \n\n➺ It is released under the supervision of the Central Board of Direct Taxes (CBDT). \n\n➺ PAN card is very useful for us as an identification proof. Through this, the Indian government gets complete information about income tax. \n\n➺ PAN card is used for all types of financial transactions. It requires income tax payment, opening a new bank account, receiving taxable salary, buying and selling property. \n\n➺ It acts like an identity card but does not have an address, so it is not used as an address proof. It looks exactly the size of a debit/credit card. \n\n➺ In this, your name, father\\'s name, date of birth, PAN number are entered. Along with this, there is also a photo and signature in it."),
    panguide2("➺ As we have already talked that PAN card is 10 character long alpha numeric unique character. \n\n➺ 1. Every PAN card number is different and unique from each other. It contains lots of information. Let us understand this with an example. \n\n➺ This number is something like this AAWA1234J \n\n➺ 2. It consists of the first 5 letters of English alphabets, followed by 4 numerical numbers, and then the last contains an English alphabet. \n\n➺ 3. In the first 5 alphabets, any letter can be between the first 3 alphabets A-Z. \n\n➺ 4. 4th alphabets are selected according to the list given below. \\10➺ For Company – C \\10➺ For any person – P \\10➺ Hindi for undivided family (HUF) – H \\10➺ For Firm – F \\10➺ For Association of persons (AOP) – A \\10➺ To denote about Trust – T \\10➺ For Individuals (BOI) - B \\10➺ Local Authority – L \\10➺ Artificial Jurisdiction Person – J \\10➺ Government – G \n\n➺ 5. 5th alphabet is the surname or last name of any person, the first letter of the name of any organization or company. \n\n➺ 6. After this, the 4 numerical digits of 6-9 characters are taken from between 0001 to 9999. \n\n➺ 7. The last digit is an alphabet which is derived from the trailing 9 characters by applying a formula."),
    panguide3("➺ This card saves you from the problems and disturbances in income tax. \n\n➺ The card issued by the Indian government is valid everywhere. It is recognized in every government office and bus train everywhere. \n\n➺ That is why you can give it in any government or private organization as ID proof. \n\n➺ Apart from full time, showing it in a part time job also makes payment easier. \n\n➺ If you do a temporary job or part time work elsewhere, then you can claim TDS in the last year of the year. \n\n➺ To transact more than 50,000. \n\n➺ With this, in the transaction of more than 50,000 amounts in the share market. \n\n➺ This works for paying more than 25,000 amount in a hotel."),
    panguide4("➺ It works as an identity card for us. When someone goes to the bank to open a bank account, it is mandatory to submit a PAN card there. Without this a bank account cannot be opened. \n\n➺ This gives tax information and the government gets information about tax evasion. \n\n➺ Apart from this, if someone comes to open his account in many banks and he feels that keeping money in different accounts will avoid the eyes of the government, then the PAN card plays the most important role in this. \n\n➺ By which the government gets to know how much total property is with him or any person."),
    panguide5("➺ Permanent account number is required for every citizen. There are many such works which are not possible without it. \n\n➺ It acts as an identity card for us in a way. In this, our name is also the father\\'s name and photo, due to which it is valid for ID proof. \n\n➺ Use it to pay income tax. If it is not there then it will not be known what is the correct amount of tax. They record all the transactions done by a person through unique numbers. This helps in preventing tax evasion. \n\n➺ This is even more important for the person doing the job. When any transaction of higher value has to be done, then it is necessary to give the details of PAN card there. Can not conduct a transaction without it. \n\n➺ It has been made mandatory to open a new bank account. If you want to make an account in any bank of India, then they will definitely ask you for this. \n\n➺ It works in getting a new connection of the telephone. \n\n➺ It is needed to buy or sell property along with this. It is necessary to build a house and buy a flat. \n\n➺ This also comes in handy for buying a vehicle. \n\n➺ You will need it to get Debit / Credit card."),
    panguide6("➺ PAN card is a mandatory requirement for transactions above Rs.50,000 (investment, deposits, etc.) and Rs.5 lakh (purchase of vehicle, jewellery, etc.). It is also an essential document while filing income tax returns and a mandatory OVD for KYC while opening an account or taking a loan. \n\n➺ A 10 digit PAN can now be provided in a personal account only for applying for a personal loan or for opening an account instead. Submitting a photocopy of the card. \n\n➺ As such, availing a personal loan without a PAN card can be a challenge as the authorities use it to track an individual\\'s financials and check monetary frauds. \n\n➺ However, some lenders may be willing to offer loans. Even without PAN card."),
    panguide7("➺ Submit other OVDs for KYC \n\n➺ In the absence of PAN card, applicants will have to submit other KYC documents, especially Aadhaar card. Other official documents along with the applicant\\'s permanent address may also suffice while applying for a personal loan without a PAN card. \n\n➺ Provide bank account details and salary slip \n\n➺ Latest bank account details like income details are required to get loan online without pan card. Lenders assess an applicant\\'s current and past financial status with these statements. \n\n➺ Financial institutions can check their fixed monthly income and expenses to have a clear overview of repayment capacity. \n\n➺ It is also mandatory to submit latest salary slip along with bank account details. People with sufficient monthly income often get preference for loan approval without a PAN card. \n\n➺ Have a CIBIL score of 750 or above \n\n➺ Those applying for instant money without a PAN card will also have to maintain a CIBIL score of 750 or more. A high score establishes an applicant\\'s credibility. It also helps in securing attractive interest rates on personal loans. \n\n➺ In the absence of a PAN card, the applicant should also have a sound repayment history. Late payment and delay can become a hindrance in this case. \n\n➺ Low Debt-to-Income Ratio or FOIR \n\n➺ A debt-to-income ratio or obligation to income ratio (FOIR) is a percentage of an individual\\'s fixed monthly liabilities against his/her income. A ratio of 50% means that he spends half of salary to meet monthly expenses. As such, disposable income gets hampered, making fresh loan EMI payments a challenge. \n\n➺ Thus, applicants should plan to reduce their fixed monthly loan to improve their chances of getting easy loan without PAN card. \n\n➺ Complying with the above points can help individuals to apply for a personal loan without a PAN card.");

    public String description;

    PanGuide(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
